### ISSUE TITLE
USER STORY <Tracking poll voting info>

### ISSUE THREAD

**Issue by aimansae** [aimansae/My-First-Agile-Progect#4]
As a  site **administrator** I can **add votes** so that **i can keep tracks** of all previous polls including voting details.

**Comment by aimansae** [comment]
## Acceptance criteria:

1. store and collect received votes
2. define expiry date for publishing poles

**Comment by aimansae** [comment]
## Tasks:

- [ ]  Update module view: poll deign CSS and HTML to include data picker 
- [ ] Add JS function to validate the expiry date is at least 3 days after
- [ ] Update controller function
- [ ] Test the functionality
